export const ZX8X_CPU_CLOCK = 3_250_000;
export const ZX8X_LINES_PER_FRAME = 312;
export const ZX8X_T_PER_LINE = 207;
export const ZX8X_T_PER_FRAME = ZX8X_T_PER_LINE * ZX8X_LINES_PER_FRAME;

export const ZX8X_ACTIVE_WIDTH = 256;
export const ZX8X_ACTIVE_HEIGHT = 192;
export const ZX8X_BORDER_LEFT = 32;
export const ZX8X_BORDER_TOP = 24;
export const ZX8X_SCREEN_WIDTH = ZX8X_ACTIVE_WIDTH + ZX8X_BORDER_LEFT * 2;
export const ZX8X_SCREEN_HEIGHT = ZX8X_ACTIVE_HEIGHT + ZX8X_BORDER_TOP * 2;
